// countries.js - ISO 3-letter code mapping to full country names
const countryCodeMap = {
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BAN': 'Bangladesh',
    'BGD': 'Bangladesh',
    'BEL': 'Belgium',
    'BHU': 'Bhutan',
    'CAN': 'Canada',
    'CRO': 'Croatia',
    'ENG': 'England',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'FIJ': 'Fiji',
    'FIN': 'Finland',
    'FRA': 'France',
    'GER': 'Germany',
    'GIB': 'Gibraltar',
    'HKG': 'Hong Kong',
    'IRL': 'Ireland',
    'ITA': 'Italy',
    'JPN': 'Japan',
    'LAO': 'Laos',
    'MAS': 'Malaysia',
    'MYA': 'Myanmar',
    'NED': 'Netherlands',
    'NOR': 'Norway',
    'POR': 'Portugal',
    'QAT': 'Qatar',
    'ROM': 'Romania',
    'SCO': 'Scotland',
    'SGP': 'Singapore',
    'SUI': 'Switzerland',
    'SVK': 'Slovakia',
    'SWE': 'Sweden',
    'THA': 'Thailand',
    'UAE': 'UAE',
    'USA': 'United States',
    'WAL': 'Wales'
};
